fixtures:
  forge_modules:
    archive:
      repo: "puppet/archive"
      ref: "3.2.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.11.0"
      flags: --verbose
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.0"
      flags: --verbose
  symlinks:
    solr5: "#{source_dir}"
